//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace АПТ.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Table
    {
        public int StudId { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Группа { get; set; }
        public int Рост { get; set; }
        public System.DateTime День_рождения { get; set; }
        public double Средний_бал { get; set; }
    }

}
